### ISSUE TITLE
Wrong colors of Windows 7 installer if theme is changed

### ISSUE THREAD

**Issue by KONEY** [samnazarko/osmc#107] opened 2015-02-24 17:57 UTC
![problem](https://cloud.githubusercontent.com/assets/5889626/6355487/aed1f874-bc56-11e4-8fff-96261b65a10b.png)

Not much to say, the screenshot is quite explanatory :) Not really a bug, but colors are quite difficult to read. Should either force both foreground and backgrond or none or them.

**Comment by samnazarko** [comment] 2015-02-25 16:35
Can't replicate this. Please provide a theme file I can try to see what the issue is.

I tried a fix (you can try the new EXE) from the OSMC website, but I doubt it will resolve the problem. I need to be able to reproduce this myself ideally if we want to fix this.

**Comment by KONEY** [comment] 2015-02-27 07:35
no problem! Just need to figure out how to attach files :)

**Comment by KONEY** [comment] 2015-02-28 12:21
Can I have your email?

**Comment by samnazarko** [comment] 2015-02-28 12:22
I can now replicate this.

I'll have a chat with @srmo as we seem to disagree about whether the background should inherit from the OS or not

S

**Comment by samnazarko** [comment] 2015-02-28 13:13
This should be fixed as of https://github.com/samnazarko/osmc/commit/762563c. 

Can you re-download the Windows installer and test?

Sam

**Comment by KONEY** [comment] 2015-02-28 13:48
Now it works, good job ;)

**Comment by samnazarko** [comment] 2015-02-28 13:48
Thank @srmo.

Closed

**Closed by samnazarko** 2015-02-28 13:48 UTC

**Comment by KONEY** [comment] 2015-02-28 13:59
May I ask the reason why the background should have been inherited, when the text color isn't?

**Comment by samnazarko** [comment] 2015-02-28 14:01
It's not meant to be inherited, it's meant to be 240,240,240 rgb

**Comment by srmo** [comment] 2015-02-28 14:09
Exactly that was the problem.

**Comment by KONEY** [comment] 2015-02-28 14:33
I was referring at the disagreement you mentioned before :)

**Comment by samnazarko** [comment] 2015-02-28 14:34
We were actually discussing a combo box background layer which looks different on some platforms such as OS X.
